name = "Matplotlib"
description = "A simple application showing how to use Matplotlib to generate a graph and display it with PyScript."
packages = ["bokeh==3.2.2", "numpy", "pandas", "panel==1.3.8","opencv-python"]

[js_modules.main]
"code.js" = "code"